"""Reader-facing export formats for episodes.

Converts a saved episode (metadata + story markdown) into clean plain text,
a standalone styled HTML document, and an EPUB ebook. The story markdown is
the canonical source; these formatters only re-shape it for reading/sharing.

Story structure conventions handled here (matching StoryGenerator.parse_days):
    "## DAY 1: Title"        -> day section
    "### Chapter 1: Title"   -> chapter within the day
"""

import html
import re
from dataclasses import dataclass, field
from typing import Any

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    margin: 0 auto; max-width: 44rem; padding: 2.5rem 1.25rem 6rem;
    font-family: Georgia, 'Iowan Old Style', 'Times New Roman', serif;
    font-size: 1.075rem; line-height: 1.75; color: #1c1a17; background: #faf8f4;
  }}
  @media (prefers-color-scheme: dark) {{
    body {{ color: #d8d3ca; background: #17150f; }}
    h1, h2, h3 {{ color: #e8e2d6; }}
    .meta {{color: #9a937f;}}
    hr {{border-color: #35301f;}}
  }}
  header.title-page {{ text-align: center; margin-bottom: 3rem; }}
  header.title-page h1 {{
    font-size: 2.1rem; line-height: 1.2; margin-bottom: .4em; letter-spacing: .02em;
  }}
  .series-line {{
    font-family: -apple-system, 'Helvetica Neue', sans-serif;
    text-transform: uppercase; letter-spacing: .28em; font-size: .72rem;
    color: #8a5a2b; margin-bottom: 1.4em;
  }}
  @media (prefers-color-scheme: dark) {{ .series-line {{color: #b98a4d;}} }}
  .meta {{ font-style: italic; font-size: .95rem; }}
  h2.day {{
    margin-top: 3.2rem; padding-bottom: .35rem; border-bottom: 1px solid #ddd5c4;
    font-size: 1.45rem;
  }}
  @media (prefers-color-scheme: dark) {{ h2.day {{border-color: #3a3320;}} }}
  h3.chapter {{ font-size: 1.13rem; margin-top: 2.1rem; }}
  figure.plate {{ margin: 2rem 0; text-align: center; }}
  figure.plate img {{ max-width: 100%; height: auto; border-radius: 4px;
    box-shadow: 0 2px 14px rgba(0,0,0,.25); }}
  p {{ margin: 0 0 1.15em; text-align: justify; hyphens: auto; }}
  footer {{ margin-top: 4rem; font-size: .82rem; text-align: center; color: inherit; opacity: .65; }}
  @media print {{
    body {{ background: #fff; color: #000; max-width: none; padding: 0; }}
    a {{ color: inherit; text-decoration: none; }}
  }}
</style>
</head>
<body>
<header class="title-page">
  <div class="series-line">Star Wars &middot; Anatomy of a Catastrophe</div>
  <h1>{title}</h1>
  <div class="meta">{meta_line}</div>
</header>
{body}
<footer>Generated by Gravedancer to General &middot; fan work &mdash; Star Wars is &copy; Lucasfilm/Disney.</footer>
</body>
</html>
"""


@dataclass
class DaySection:
    number: int
    title: str
    chapters: list[dict[str, Any]] = field(default_factory=list)
    intro: str = ""

    @property
    def heading(self) -> str:
        return f"Day {self.number}: {self.title}"


_DAY_RE = re.compile(r"^##\s+DAY\s+(\d+)\s*[:\-–]\s*(.+?)\s*$", re.MULTILINE)
_CHAPTER_RE = re.compile(r"^###\s+(?:Chapter\s+)?(\d+)\s*[:\-–]\s*(.+?)\s*$", re.MULTILINE)


def parse_story_sections(story_md: str) -> list[DaySection]:
    """Split story markdown into day sections with chapter blocks."""
    if not story_md or not story_md.strip():
        return []
    text = story_md.strip()
    day_matches = list(_DAY_RE.finditer(text))
    if not day_matches:
        # Unstructured story: one anonymous section holding all prose.
        body = _strip_leading_frontmatter(text)
        return [DaySection(number=1, title="Story", intro=body)] if body else []

    sections: list[DaySection] = []
    preamble_end = day_matches[0].start()
    for i, match in enumerate(day_matches):
        start = match.end()
        end = day_matches[i + 1].start() if i + 1 < len(day_matches) else len(text)
        chunk = text[start:end]
        section = DaySection(number=int(match.group(1)), title=match.group(2).strip())

        chapter_matches = list(_CHAPTER_RE.finditer(chunk))
        if chapter_matches:
            intro = chunk[: chapter_matches[0].start()].strip()
            if intro:
                section.intro = intro
            for j, cm in enumerate(chapter_matches):
                c_start = cm.end()
                c_end = chapter_matches[j + 1].start() if j + 1 < len(chapter_matches) else len(chunk)
                section.chapters.append({
                    "number": int(cm.group(1)),
                    "title": cm.group(2).strip(),
                    "text": chunk[c_start:c_end].strip(),
                })
        else:
            section.intro = chunk.strip()
        sections.append(section)
    del preamble_end
    return sections


def _strip_leading_frontmatter(text: str) -> str:
    """Drop '# Title', '**Generated:** ...' headers and leading separators."""
    lines = text.splitlines()
    out: list[str] = []
    seen_separator = False
    for line in lines:
        stripped = line.strip()
        if not seen_separator and (
            stripped.startswith("# ")
            or stripped.startswith("**")
            or stripped == "---"
            or not stripped
        ):
            if stripped == "---":
                seen_separator = True
            continue
        out.append(line)
    return "\n".join(out).strip()


def episode_meta_line(metadata: dict[str, Any], num_days: int | None = None) -> str:
    jedi = metadata.get("jedi_name") or metadata.get("target_jedi_name") or ""
    days = num_days if num_days is not None else metadata.get("num_days", "")
    setting = metadata.get("setting", "")
    parts = []
    if days:
        parts.append(f"{days} days" if isinstance(days, int) else str(days))
    if jedi:
        parts.append(f"Target Jedi: {jedi}")
    if setting:
        short = setting.split(".")[0].strip()
        parts.append(short)
    return " · ".join(parts)


# ── Plain text ──────────────────────────────────────────────────────────────

def to_plain_text(title: str, story_md: str, metadata: dict[str, Any] | None = None,
                  width: int = 78) -> str:
    """Clean, wrapped plain-text rendering of the episode."""
    import textwrap

    meta = metadata or {}
    sections = parse_story_sections(story_md)
    lines: list[str] = []

    def rule(char: str = "=") -> str:
        return char * min(width, 72)

    lines.append(title.upper())
    lines.append(rule())
    meta_line = episode_meta_line(meta)
    if meta_line:
        lines.extend(textwrap.wrap(meta_line, width=width) or [""])
        lines.append("")
    for i, sec in enumerate(sections):
        if i:
            lines.append("")
        lines.append(f"{sec.heading.upper()}")
        lines.append(rule("-"))
        lines.append("")
        if sec.intro:
            lines.extend(_wrap_paragraphs(sec.intro, width))
        for ch in sec.chapters:
            lines.append("")
            lines.append(f"Chapter {ch['number']}: {ch['title']}")
            lines.append("")
            lines.extend(_wrap_paragraphs(ch["text"], width))
    return "\n".join(lines).strip() + "\n"


def _wrap_paragraphs(md_text: str, width: int) -> list[str]:
    import textwrap

    wrapped: list[str] = []
    for para in md_text.split("\n\n"):
        para = para.strip()
        if not para:
            continue
        # Light markdown cleanup for plain text.
        para = re.sub(r"\*\*(.+?)\*\*", r"\1", para, flags=re.DOTALL)
        para = re.sub(r"\*(.+?)\*", r"\1", para)
        para = re.sub(r"`(.+?)`", r"\1", para)
        wrapped.extend(textwrap.wrap(para, width=width) or [""])
        wrapped.append("")
    if wrapped and wrapped[-1] == "":
        wrapped.pop()
    return wrapped


# ── HTML ────────────────────────────────────────────────────────────────────

def to_html(title: str, story_md: str, metadata: dict[str, Any] | None = None,
            images: dict[str, bytes] | None = None) -> str:
    """Render the episode as standalone HTML.

    ``images`` maps image keys ("banner", "day-1", "day-1-ch2", ...) to PNG
    bytes; matching images are embedded inline (base64) at their positions.
    """
    meta = metadata or {}
    images = images or {}
    sections = parse_story_sections(story_md)

    def _img_tag(key: str) -> str:
        data = images.get(key)
        if not data:
            return ""
        import base64
        b64 = base64.b64encode(data).decode("ascii")
        return (
            f'<figure class="plate"><img src="data:image/png;base64,{b64}" '
            f'alt="{html.escape(key)}"></figure>'
        )

    body_parts: list[str] = []
    cover = _img_tag("banner")
    if cover:
        body_parts.append(cover)
    for sec in sections:
        body_parts.append(f'<h2 class="day" id="day-{sec.number}">{html.escape(sec.heading)}</h2>')
        plate = _img_tag(f"day-{sec.number}")
        if plate:
            body_parts.append(plate)
        if sec.intro:
            body_parts.append(_md_to_html_paragraphs(sec.intro))
        for ch in sec.chapters:
            body_parts.append(
                f'<h3 class="chapter">Chapter {ch["number"]}: {html.escape(ch["title"])}</h3>'
            )
            ch_plate = _img_tag(f"day-{sec.number}-ch{ch['number']}")
            if ch_plate:
                body_parts.append(ch_plate)
            body_parts.append(_md_to_html_paragraphs(ch["text"]))
    return HTML_TEMPLATE.format(
        title=html.escape(title),
        meta_line=html.escape(episode_meta_line(meta)),
        body="\n".join(body_parts),
    )


def _md_to_html_paragraphs(md_text: str) -> str:
    paras = []
    for para in md_text.split("\n\n"):
        para = para.strip()
        if not para:
            continue
        para = html.escape(para)
        para = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", para, flags=re.DOTALL)
        para = re.sub(r"\*(.+?)\*", r"<em>\1</em>", para)
        paras.append(f"<p>{para}</p>")
    return "\n".join(paras)


# ── EPUB ────────────────────────────────────────────────────────────────────

def to_epub_bytes(title: str, story_md: str, metadata: dict[str, Any] | None = None,
                  cover_image: bytes | None = None,
                  cover_media_type: str = "image/png",
                  images: dict[str, bytes] | None = None) -> bytes:
    """Build an EPUB 3 ebook: title page + one chapter per day.

    ``images`` maps keys ("banner", "day-1", "day-1-ch2", ...) to PNG bytes;
    matching images are embedded at their chapter positions.
    """
    from ebooklib import epub

    meta = metadata or {}
    images = images or {}
    book = epub.EpubBook()
    identifier = f"gravedancer:{_slug(title)}"
    book.set_identifier(identifier)
    book.set_title(title)
    book.set_language("en")
    author = "Gravedancer to General"
    book.add_author(author)

    style = """
    body { font-family: serif; line-height: 1.7; }
    h1 { text-align: center; margin-top: 20%; }
    h2 { margin-top: 2em; border-bottom: 1px solid #999; padding-bottom: .2em; }
    .meta { text-align: center; font-style: italic; }
    p { text-indent: 1.2em; margin: 0 0 .6em; }
    figure.plate { margin: 1.5em 0; text-align: center; page-break-inside: avoid; }
    figure.plate img { max-width: 100%; height: auto; }
    """
    css = epub.EpubItem(uid="style", file_name="style/main.css",
                         media_type="text/css", content=style.encode("utf-8"))
    book.add_item(css)

    if cover_image:
        book.set_cover(f"cover.{cover_media_type.split('/')[-1]}", cover_image)

    sections = parse_story_sections(story_md)

    title_content = [
        "<h1>" + html.escape(title) + "</h1>",
        '<p class="meta">' + html.escape(episode_meta_line(meta)) + "</p>",
        "<p>&nbsp;</p><p><em>Anatomy of a Catastrophe — a Star Wars fan series "
        "chronicling Qymaen jai Sheelal's evolution into General Grievous.</em></p>",
    ]
    title_page = epub.EpubHtml(title=title, file_name="title.xhtml", lang="en")
    title_page.content = "".join(title_content)
    title_page.add_item(css)
    book.add_item(title_page)

    spine = ["nav", title_page]
    toc = [title_page]

    def _embed_image(key: str, idx: int) -> tuple[str, Any | None]:
        """Add an image to the book and return (xhtml img tag, item)."""
        data = images.get(key)
        if not data:
            return "", None
        item = epub.EpubItem(
            uid=f"img{idx}", file_name=f"images/{key}.png",
            media_type="image/png", content=data)
        book.add_item(item)
        tag = (f'<figure class="plate"><img src="images/{key}.png" '
               f'alt="{html.escape(key)}"/></figure>')
        return tag, item

    img_idx = 0
    banner_tag, _ = _embed_image("banner", img_idx)
    img_idx += 1
    if banner_tag:
        title_content.append(banner_tag)
    title_page.content = "".join(title_content)

    for sec in sections:
        chapter = epub.EpubHtml(
            title=sec.heading,
            file_name=f"day-{sec.number}.xhtml",
            lang="en",
        )
        parts = [f"<h2>{html.escape(sec.heading)}</h2>"]
        day_tag, _ = _embed_image(f"day-{sec.number}", img_idx)
        img_idx += 1
        if day_tag:
            parts.append(day_tag)
        if sec.intro:
            parts.append(_md_to_html_paragraphs(sec.intro))
        for ch in sec.chapters:
            parts.append(
                f"<h3>Chapter {ch['number']}: {html.escape(ch['title'])}</h3>"
            )
            ch_tag, _ = _embed_image(f"day-{sec.number}-ch{ch['number']}", img_idx)
            img_idx += 1
            if ch_tag:
                parts.append(ch_tag)
            parts.append(_md_to_html_paragraphs(ch["text"]))
        chapter.content = "".join(parts)
        chapter.add_item(css)
        book.add_item(chapter)
        spine.append(chapter)
        toc.append(chapter)

    book.toc = list(toc)  # type: ignore[assignment]
    book.spine = spine  # type: ignore[assignment]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    import io
    buf = io.BytesIO()
    epub.write_epub(buf, book)
    return buf.getvalue()


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "episode"


def suggest_file_stem(episode_id: str, title: str) -> str:
    """File name stem shared by every export format."""
    stem = _slug(title)[:60]
    date_part = episode_id.split("-")[1] if "-" in episode_id else ""
    return f"{date_part}-{stem}" if date_part else stem
